#pragma once

#include "../Device.hpp"
#include "All.hpp"

/// Every chip description there is, as one type list: what a test walks that has something to say
/// about all of them -- the identity stage against each description's own `Identity`
/// (test/i2c/oracle_test.cpp), a foreign part at each address (identify_test.cpp), and
/// i2c_testing's hardware test compiled for every one (src/hwtest/all.cpp there). A new
/// description gets a line here, and those tests pick it up.
///
/// With their default parameters. A part whose address is only ever the board's has no default
/// and is named with one here, for the tests' sake: the AD7291 and the LMK1D1208I (strapped over
/// a range), the PCA9956B (strapped, and its Rext is the board's).
namespace Kvasir::I2C::Chips {

using Every = List<Chips::Ad5665,
                   Chips::Ads1015<>,
                   Chips::Ads1115<>,
                   Chips::Ads1219<>,
                   Chips::Adt7420<>,
                   Chips::Adxl345,
                   Chips::Aht20,
                   Chips::Aled7709<>,
                   Chips::Apds9960<>,
                   Chips::As5600,
                   Chips::As7341<>,
                   Chips::At24c02,
                   Chips::At24c32,
                   Chips::At24c512,
                   Chips::Axp2101,
                   Chips::Bh1750,
                   Chips::Bma456<>,
                   Chips::Bme280,
                   Chips::Bmp280,
                   Chips::Bmp180<>,
                   Chips::Cy15b064j<>,
                   Chips::SparkFunSoilMoisture,
                   Chips::Dht20,
                   Chips::Dps310<>,
                   Chips::Ds1307,
                   Chips::Ds3231,
                   Chips::Ds3502<>,
                   Chips::Eeprom24aa025e48<>,
                   Chips::Emc2101,
                   Chips::Es8311<>,
                   Chips::Lcd1602,
                   Chips::Lcd2004,
                   Chips::Hdc1080,
                   Chips::Hmc5883l,
                   Chips::Ht16k33,
                   Chips::Htu21d,
                   Chips::Si7021,
                   Chips::Iis2dulpx<>,
                   Chips::Ina219<>,
                   Chips::Ina226<>,
                   Chips::Ina228<>,
                   Chips::Ina237<>,
                   Chips::Ina238<>,
                   Chips::Ina3221<>,
                   Chips::Ktd2026<>,
                   Chips::Ktd2061<>,
                   Chips::Lis3dh,
                   Chips::Lm75,
                   Chips::Lsm303agrAccel<>,
                   Chips::Lsm303agrMag<>,
                   Chips::Lsm6ds3,
                   Chips::Lsm6dso,
                   Chips::Lsm9ds1Ag<>,
                   Chips::Lsm9ds1Mag<>,
                   Chips::Ltr390<>,
                   Chips::Ltr507<>,
                   Chips::Mcp23017,
                   Chips::Mcp3221<>,
                   Chips::Mcp3421,
                   Chips::Mcp4018<>,
                   Chips::Mcp4725<>,
                   Chips::Mcp47a1<>,
                   Chips::Mcp9808,
                   Chips::Mlx90614<>,
                   Chips::Mma8451,
                   Chips::Ssd1306<>,
                   Chips::Ssd1315<>,
                   Chips::Ssd1309<>,
                   Chips::Sh1106<>,
                   Chips::Mpl3115a2,
                   Chips::Mpr121<>,
                   Chips::Mpu6050,
                   Chips::Nau7802<>,
                   Chips::Opt3001<>,
                   Chips::Opt4048<>,
                   Chips::Pa1010d<>,
                   Chips::Pca9557,
                   Chips::Pca9685<>,
                   Chips::Pcf85063a<>,
                   Chips::Pcf8574,
                   Chips::Pcf8575,
                   Chips::Qmi8658<>,
                   Chips::Rv8803<>,
                   Chips::Scd4x,
                   Chips::Sgp40,
                   Chips::Sht3x,
                   Chips::Sht4x,
                   Chips::Shtc3,
                   Chips::SolderedRotary<>,
                   Chips::SolderedSlider<>,
                   Chips::Tca9548a,
                   Chips::Tca9555,
                   Chips::Tcs34725,
                   Chips::Tlv493d,
                   Chips::Tmag5273<>,
                   Chips::Tmp102,
                   Chips::Tmp1075,
                   Chips::Tmp117,
                   Chips::Tmp119,
                   Chips::Cst816s<>,
                   Chips::Cst9217<>,
                   Chips::Ft6x36<>,
                   Chips::Gt911<>,
                   Chips::Tsl2561,
                   Chips::Tsl2591<>,
                   Chips::SamM8q<>,
                   Chips::Vcnl4040,
                   Chips::Veml6030<>,
                   Chips::Veml7700<>,
                   Chips::Vl53l1x,
                   Chips::Ad7291<0x2F>,
                   Chips::Lmk1d1208i<0x68>,
                   Chips::Pca9956b<0x3F, Units::ohm(2200)>>;

}   // namespace Kvasir::I2C::Chips
